version: "3"

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: interview
      MYSQL_USER: wladi
      MYSQL_PASSWORD: secret

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php
    restart: always

volumes:
  db_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: /docker/mysql
