version: "3"

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations:/home/migrations
    command: --default-authentication-plugin=mysql_native_password --init-file=/home/migrations/init.sql --bind-address=0.0.0.0
    ports:
      - "3310:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: interview
      MYSQL_USER: wladi
      MYSQL_PASSWORD: secret
    networks:
      - interview-network

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    restart: always
    networks:
      - interview-network

  nginx:
    image: nginx:latest
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php
    restart: always
    networks:
      - interview-network

volumes:
  db_data:
    driver: local

networks:
  interview-network:
    driver: bridge
